// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id,username,ratings)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
`

type CreateUserParams struct {
	Username string
	Ratings  int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Ratings)
	return err
}
