// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const batchUpdateUserRating = `-- name: BatchUpdateUserRating :exec
UPDATE users
SET ratings=updates.new_rating
FROM(
    SELECT
        UNNEST($1::text[]) AS username,
        UNNEST($2::int[]) AS new_rating
) AS updates
WHERE users.username=updates.username
`

type BatchUpdateUserRatingParams struct {
	Column1 []string
	Column2 []int32
}

func (q *Queries) BatchUpdateUserRating(ctx context.Context, arg BatchUpdateUserRatingParams) error {
	_, err := q.db.ExecContext(ctx, batchUpdateUserRating, pq.Array(arg.Column1), pq.Array(arg.Column2))
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id,username,ratings)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
`

type CreateUserParams struct {
	Username string
	Ratings  int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Ratings)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT username,ratings
FROM users
`

type GetAllUsersRow struct {
	Username string
	Ratings  int32
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.Username, &i.Ratings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomUsers = `-- name: GetRandomUsers :many
SELECT username
FROM users
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomUsers(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRandomUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
